### ISSUE TITLE
Add a specialization for `evalpoly` for `Polynomial{BigFloat}` here or to Polynomials or?

### ISSUE THREAD

**Issue by nsajko** [jverzani/PolynomialsMutableArithmetics.jl#2]
I want to evaluate some `Polynomial{BigFloat}` faster, so I'm wondering where (to which package) am I supposed to submit a specialization that would use MutableArithmetics?

**Comment by nsajko** [comment]
Just realized it makes more sense to specialize for just the `Vector{BigFloat}` coefficients than for `Polynomial{BigFloat}`.

**Comment by jverzani** [comment]
Anyway, I think to answer your original question, the MutableArithmetics extension in Polynomials is likely the best place. I expect this package to languish.
